pipeline:
  build:
    image: amarburg/camera-calibration-dev-host:latest
    pull:  true
    commands:
          - ./fips set config linux-make-unittest
          - ./fips build

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status:
        - success
        - failure
